signon: src/signond/main.cpp File Reference
main.cpp File Reference
#include "signondaemon.h"
#include <QtCore>
Functions
void installSigHandlers ()
int main (int argc, char *argv[])
Function Documentation
void installSigHandlers ()
Definition at line 29 of file main.cpp.
References SignonDaemonNS::SignonDaemon::signalHandler().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 41 of file main.cpp.
References installSigHandlers(), and SignonDaemonNS::SignonDaemon::instance().