signon: SignonDaemonNS::SignonIdentityInfo Struct Reference
SignonDaemonNS::SignonIdentityInfo Struct Reference
Daemon side representation of identity information.
#include <signonidentityinfo.h>
Public Member Functions
SignonIdentityInfo ()
SignonIdentityInfo (const QVariantMap &info)
SignonIdentityInfo (const quint32 id, const QString &userName, const QString &password, const bool storePassword, const QString &caption, const MethodMap &methods, const QStringList &realms=QStringList(), const QStringList &accessControlList=QStringList(), const QStringList &ownerList=QStringList(), int type=0, int refCount=0, bool validated=false)
const QVariantMap toMap () const
bool operator== (const SignonIdentityInfo &other) const
SignonIdentityInfo & operator= (const SignonIdentityInfo &other)
void setNew ()
bool isNew () const
void setId (quint32 id)
quint32 id () const
void setUserName (const QString &userName)
QString userName () const
void setUserNameSecret (bool secret)
bool isUserNameSecret () const
void setPassword (const QString &password)
QString password () const
void setStorePassword (bool storePassword)
bool storePassword () const
void setCaption (const QString &caption)
QString caption () const
void setRealms (const QStringList &realms)
QStringList realms () const
void setMethods (const MethodMap &methods)
MethodMap methods () const
void setAccessControlList (const QStringList &acl)
QStringList accessControlList () const
void setValidated (bool validated)
bool validated () const
void setType (const int type)
int type () const
void setOwnerList (const QStringList &owner)
QStringList ownerList () const
bool checkMethodAndMechanism (const QString &method, const QString &mechanism, QString &allowedMechanism)
Detailed Description
Daemon side representation of identity information.
Todo:
description.
Definition at line 43 of file signonidentityinfo.h.
Constructor & Destructor Documentation
SignonDaemonNS::SignonIdentityInfo::SignonIdentityInfo ()
Definition at line 31 of file signonidentityinfo.cpp.
SignonDaemonNS::SignonIdentityInfo::SignonIdentityInfo (const QVariantMap & info)
Definition at line 48 of file signonidentityinfo.cpp.
SignonDaemonNS::SignonIdentityInfo::SignonIdentityInfo (const quint32 id, const QString & userName, const QString & password, const bool storePassword, const QString & caption, const MethodMap & methods, const QStringList & realms = QStringList(), const QStringList & accessControlList = QStringList(), const QStringList & ownerList = QStringList(), int type = 0, int refCount = 0, bool validated = false)
Definition at line 79 of file signonidentityinfo.cpp.
Member Function Documentation
QStringList SignonDaemonNS::SignonIdentityInfo::accessControlList () const inline
Definition at line 94 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::MetaDataDB::updateIdentity().
QString SignonDaemonNS::SignonIdentityInfo::caption () const inline
Definition at line 83 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::SignonIdentity::requestCredentialsUpdate(), setCaption(), and SignonDaemonNS::SignonIdentity::verifyUser().
bool SignonDaemonNS::SignonIdentityInfo::checkMethodAndMechanism (const QString & method, const QString & mechanism, QString & allowedMechanism)
Definition at line 156 of file signonidentityinfo.cpp.
Referenced by SignonDaemonNS::SignonAuthSessionAdaptor::process().
quint32 SignonDaemonNS::SignonIdentityInfo::id () const inline
Definition at line 68 of file signonidentityinfo.h.
Referenced by setId(), SignonDaemonNS::MetaDataDB::updateIdentity(), and SignonDaemonNS::SignonIdentity::verifySecret().
bool SignonDaemonNS::SignonIdentityInfo::isNew () const inline
Definition at line 66 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::CredentialsDB::credentials(), SignonDaemonNS::SignonDaemon::getIdentity(), SignonDaemonNS::SignonIdentity::getInfo(), SignonDaemonNS::CredentialsDB::insertCredentials(), SignonDaemonNS::SignonIdentity::storeCredentials(), and SignonDaemonNS::MetaDataDB::updateIdentity().
bool SignonDaemonNS::SignonIdentityInfo::isUserNameSecret () const inline
Definition at line 73 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::CredentialsDB::checkPassword(), SignonDaemonNS::CredentialsDB::credentials(), and SignonDaemonNS::CredentialsDB::updateCredentials().
MethodMap SignonDaemonNS::SignonIdentityInfo::methods () const inline
Definition at line 90 of file signonidentityinfo.h.
Referenced by setMethods(), and SignonDaemonNS::MetaDataDB::updateIdentity().
SignonIdentityInfo & SignonDaemonNS::SignonIdentityInfo::operator= (const SignonIdentityInfo & other)
Definition at line 203 of file signonidentityinfo.cpp.
bool SignonDaemonNS::SignonIdentityInfo::operator== (const SignonIdentityInfo & other) const
Definition at line 127 of file signonidentityinfo.cpp.
QStringList SignonDaemonNS::SignonIdentityInfo::ownerList () const inline
Definition at line 103 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::MetaDataDB::updateIdentity().
QString SignonDaemonNS::SignonIdentityInfo::password () const inline
Definition at line 76 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::SignonIdentity::queryInfo(), setPassword(), SignonDaemonNS::CredentialsDB::updateCredentials(), SignonDaemonNS::SignonIdentity::verifyUiSlot(), and SignonDaemonNS::SignonIdentity::verifyUser().
QStringList SignonDaemonNS::SignonIdentityInfo::realms () const inline
Definition at line 86 of file signonidentityinfo.h.
Referenced by setRealms(), and SignonDaemonNS::MetaDataDB::updateIdentity().
void SignonDaemonNS::SignonIdentityInfo::setAccessControlList (const QStringList & acl) inline
Definition at line 92 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setCaption (const QString & caption) inline
Definition at line 82 of file signonidentityinfo.h.
References caption().
Referenced by SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setId (quint32 id) inline
Definition at line 67 of file signonidentityinfo.h.
References id().
void SignonDaemonNS::SignonIdentityInfo::setMethods (const MethodMap & methods) inline
Definition at line 88 of file signonidentityinfo.h.
References methods().
Referenced by SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setNew () inline
Definition at line 65 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::CredentialsDB::insertCredentials().
void SignonDaemonNS::SignonIdentityInfo::setOwnerList (const QStringList & owner) inline
Definition at line 102 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setPassword (const QString & password) inline
Definition at line 75 of file signonidentityinfo.h.
References password().
Referenced by SignonDaemonNS::CredentialsDB::credentials(), SignonDaemonNS::SignonIdentity::queryInfo(), SignonDaemonNS::SignonIdentity::queryUiSlot(), and SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setRealms (const QStringList & realms) inline
Definition at line 85 of file signonidentityinfo.h.
References realms().
Referenced by SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setStorePassword (bool storePassword) inline
Definition at line 77 of file signonidentityinfo.h.
References storePassword().
Referenced by SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setType (const int type) inline
Definition at line 99 of file signonidentityinfo.h.
References type().
Referenced by SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setUserName (const QString & userName) inline
Definition at line 70 of file signonidentityinfo.h.
References userName().
Referenced by SignonDaemonNS::CredentialsDB::credentials(), and SignonDaemonNS::SignonIdentity::store().
void SignonDaemonNS::SignonIdentityInfo::setUserNameSecret (bool secret) inline
Definition at line 72 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::MetaDataDB::identity().
void SignonDaemonNS::SignonIdentityInfo::setValidated (bool validated) inline
Definition at line 96 of file signonidentityinfo.h.
References validated().
bool SignonDaemonNS::SignonIdentityInfo::storePassword () const inline
Definition at line 80 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::CredentialsDB::credentials(), SignonDaemonNS::SignonIdentity::requestCredentialsUpdate(), setStorePassword(), SignonDaemonNS::CredentialsDB::updateCredentials(), and SignonDaemonNS::SignonIdentity::verifyUser().
const QVariantMap SignonDaemonNS::SignonIdentityInfo::toMap () const
Definition at line 107 of file signonidentityinfo.cpp.
Referenced by SignonDaemonNS::SignonDaemon::getIdentity(), SignonDaemonNS::SignonIdentity::getInfo(), and SignonDaemonNS::SignonDaemon::queryIdentities().
int SignonDaemonNS::SignonIdentityInfo::type () const inline
Definition at line 100 of file signonidentityinfo.h.
Referenced by setType().
QString SignonDaemonNS::SignonIdentityInfo::userName () const inline
Definition at line 71 of file signonidentityinfo.h.
Referenced by SignonDaemonNS::CredentialsDB::checkPassword(), SignonDaemonNS::SignonIdentity::requestCredentialsUpdate(), setUserName(), SignonDaemonNS::CredentialsDB::updateCredentials(), SignonDaemonNS::SignonIdentity::verifySecret(), and SignonDaemonNS::SignonIdentity::verifyUser().
bool SignonDaemonNS::SignonIdentityInfo::validated () const inline
Definition at line 97 of file signonidentityinfo.h.
Referenced by setValidated().
The documentation for this struct was generated from the following files:
src/signond/signonidentityinfo.h
src/signond/signonidentityinfo.cpp